// LoRa
Blockly.Msg.WEBDUINO_LORA_SEND_STRING = "傳送字串";
Blockly.Msg.WEBDUINO_LORA_SUCCESS_CALLBACK = "成功後執行";
Blockly.Msg.WEBDUINO_LORA_FAIL_CALLBACK = "失敗後執行";
Blockly.Msg.WEBDUINO_LORA_RECEIVE_CALLBACK = "接收字串後執行";
Blockly.Msg.WEBDUINO_LORA_RECEIVED_STRING = "接收的字串";